# Generated by Django 3.2.6 on 2022-12-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_description', models.CharField(max_length=500)),
                ('logical_doc_id', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
    ]
